In [1]:
import numpy as np
import scipy.special

# Lesson 26

In [2]:
my_ar = np.array([1, 2, 3, 4])

my_ar

array([1, 2, 3, 4])

In [3]:
my_ar.dtype

dtype('int64')

In [4]:
my_ar.shape

(4,)

In [5]:
my_ar.astype(float)

array([1., 2., 3., 4.])

In [8]:
print(my_ar.max())
print(my_ar.min())
print(my_ar.sum())
print(my_ar.mean())
print(my_ar.std())

4
1
10
2.5
1.118033988749895


In [9]:
print(np.max(my_ar))
print(np.min(my_ar))
print(np.sum(my_ar))
print(np.mean(my_ar))
print(np.std(my_ar))

4
1
10
2.5
1.118033988749895


In [10]:
n=10

np.zeros(n)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(n)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(n)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
my_ar = np.array([[1, 2], [3, 4]])
np.zeros_like(my_ar)

array([[0, 0],
       [0, 0]])

In [15]:
my_ar = np.array([1, 2, 3, 4])

np.exp(my_ar)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
np.cos(my_ar)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [17]:
np.sqrt(my_ar)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [18]:
np.dot(my_ar, my_ar)

30

In [19]:
np.pi

3.141592653589793

In [20]:
scipy.special.erf(my_ar)

array([0.84270079, 0.99532227, 0.99997791, 0.99999998])

In [21]:
print(sum(my_ar))

10


In [22]:
x = np.random.random(10000)

def python_sum(x):
    x_sum = 0.0
    for y in x:
        x_sum += y
    return x_sum

%timeit python_sum(x)

934 µs ± 12.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%timeit np.sum(x)

5.96 µs ± 109 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Lesson 27